# -*- coding: utf-8 -*-
"""Task6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g063YGu25ZKawhCB0nKAjIfY3ELYzeDy
"""

query1 = """
SELECT
    strftime('%Y', InvoiceDate) AS year,
    strftime('%m', InvoiceDate) AS month,
    SUM((Quantity * UnitPrice) - Discount + ShippingCost) AS monthly_revenue,
    COUNT(DISTINCT InvoiceNo) AS total_orders
FROM online_sales
GROUP BY year, month
ORDER BY year, month;
"""
pd.read_sql(query1, conn)

# Top 3 Months by Revenue
query2 = """
SELECT
    strftime('%Y-%m', InvoiceDate) AS month_year,
    SUM((Quantity * UnitPrice) - Discount + ShippingCost) AS monthly_revenue
FROM online_sales
GROUP BY month_year
ORDER BY monthly_revenue DESC
LIMIT 3;
"""
pd.read_sql(query2, conn)

# Yearly Revenue Trend
query3 = """
SELECT
    strftime('%Y', InvoiceDate) AS year,
    SUM((Quantity * UnitPrice) - Discount + ShippingCost) AS yearly_revenue
FROM online_sales
GROUP BY year
ORDER BY year;
"""
pd.read_sql(query3, conn)

# Best-Selling Categories
query4 = """
SELECT
    Category,
    SUM(Quantity) AS total_units_sold,
    SUM((Quantity * UnitPrice) - Discount + ShippingCost) AS total_revenue
FROM online_sales
GROUP BY Category
ORDER BY total_revenue DESC
LIMIT 5;
"""
pd.read_sql(query4, conn)

# Best-Selling Products
query5 = """
SELECT
    Description AS product_name,
    SUM(Quantity) AS total_units_sold,
    SUM((Quantity * UnitPrice) - Discount + ShippingCost) AS total_revenue
FROM online_sales
GROUP BY product_name
ORDER BY total_revenue DESC
LIMIT 5;
"""
pd.read_sql(query5, conn)